server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true

database:
  default:
    link:   "sqlite::@file(manifest/document/sqlite/marmot.db)"

inspection:
  mysql: 
    enabled: true
    url: "mysql:root:coding123@tcp(127.0.0.1:3306)"
    items:
      - name: 创建数据库
        cmds: 
          - "create database test2"
      - name: 删除数据库
        cmds: 
          - "drop database test2"

