// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Inspection is the golang structure of table inspection for DAO operations like Where/Data.
type Inspection struct {
	g.Meta       `orm:"table:inspection, do:true"`
	Id           interface{}       `json:"id"`
	Name         interface{}    `json:"name"`
	Count        interface{}       `json:"count"`
	SuccessCount interface{}       `json:"successCount"`
	FailedCount  interface{}       `json:"failedCount"`
	Connection   interface{}      `json:"connection"`
	Availability interface{}      `json:"availability"`
	StartTime    *gtime.Time //
	EndTime      *gtime.Time //
}
