// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// InspectionDetail is the golang structure of table inspection_detail for DAO operations like Where/Data.
type InspectionDetail struct {
	g.Meta        `orm:"table:inspection_detail, do:true"`
	Id            interface{} //
	InspectTaskId interface{} //
	Name          interface{} //
	ExecStatus    interface{} //
	ErrMsg        interface{} //
	StartTime     *gtime.Time //
	EndTime       *gtime.Time //
	InspectionId  interface{} //
}
