// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"marmot/internal/dao/internal"
)

// internalInspectionDao is internal type for wrapping internal DAO implements.
type internalInspectionDao = *internal.InspectionDao

// inspectionDao is the data access object for table inspection.
// You can define custom methods on it to extend its functionality as you wish.
type inspectionDao struct {
	internalInspectionDao
}

var (
	// Inspection is globally public accessible object for table inspection operations.
	Inspection = inspectionDao{
		internal.NewInspectionDao(),
	}
)

// Fill with you ideas below.
