// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"marmot/internal/dao/internal"
)

// internalInspectionDetailDao is internal type for wrapping internal DAO implements.
type internalInspectionDetailDao = *internal.InspectionDetailDao

// inspectionDetailDao is the data access object for table inspection_detail.
// You can define custom methods on it to extend its functionality as you wish.
type inspectionDetailDao struct {
	internalInspectionDetailDao
}

var (
	// InspectionDetail is globally public accessible object for table inspection_detail operations.
	InspectionDetail = inspectionDetailDao{
		internal.NewInspectionDetailDao(),
	}
)

// Fill with you ideas below.
