// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// InspectionDetail is the golang structure for table inspection_detail.
type InspectionDetail struct {
	Id           int         `json:"id"           ` //
	Name         string      `json:"name"         ` //
	Success      bool        `json:"success"      ` //
	ErrMsg       string      `json:"errMsg"       ` //
	StartTime    *gtime.Time `json:"startTime"    ` //
	EndTime      *gtime.Time `json:"endTime"      ` //
	InspectionId int         `json:"inspectionId" ` //
}
